### ISSUE TITLE
What languages are supported by this extension?

### ISSUE THREAD

**Issue by IceSentry** [kbysiec/vscode-search-everywhere#27]
I tried using it in a rust project and it didn't find anything, but when I opened a typescript project it worked as expected.

Is this normal? I assumed it simply used any language server associated with the currently opened project. I can definitely search by symbols like normally, so it's not that vscode can't do it from what I can see.

**Comment by kbysiec** [comment]
Hi,

You have to modify the following setting:

searchEverywhere.include

String with include pattern. Any file matching this glob will be included in indexing.

Default value:

"**/*.{js,jsx,ts,tsx}"


Typescript files are supported by default because of the default value of this setting.
Hope it helps.

Regards,
Kamil

**Comment by IceSentry** [comment]
Thank you, that makes sense. 

In that case, you should probably make this information higher up in the README or have a specific language support section to explain this. It was not obvious to me that the issue was a wrong filter.

**Comment by kbysiec** [comment]
Sure, thanks for suggestion. I will keep it in mind updating the readme next time.

Regards,
Kamil
